[package]
name = "z3-rust-tutorial"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
z3 ="0.11.2"
z3-sys = "0.7.1"